spark.sql.extensions org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
spark.sql.catalog.lakehouse org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.lakehouse.type rest
spark.sql.catalog.lakehouse.uri http://polaris:8181/api/catalog
spark.sql.catalog.lakehouse.oauth2-server-uri http://polaris:8181/api/catalog/v1/oauth/tokens
spark.sql.catalog.lakehouse.warehouse lakehouse
spark.sql.catalog.lakehouse.scope PRINCIPAL_ROLE:ALL
spark.sql.catalog.lakehouse.rest.auth.type oauth2
spark.sql.catalog.lakehouse.header.X-Iceberg-Access-Delegation vended-credentials
spark.sql.catalog.lakehouse.token-refresh-enabled true
spark.sql.catalogImplementation in-memory
spark.sql.session.timeZone UTC
spark.sql.defaultCatalog lakehouse
spark.serializer org.apache.spark.serializer.KryoSerializer
