[project]
name = "batch-pipeline"
version = "0.1.0"
requires-python = ">=3.11,<3.12"
dependencies = [
  "PyYAML==6.0.2",
  "pymysql==1.1.1",
  "boto3==1.35.99",
  "pyarrow==17.0.0",
]

[project.optional-dependencies]
dev = ["pytest==8.4.1"]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-dir]
"" = "src"