"""initial schema - 12 OLTP tables

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-07-24

Explicit (non-autogenerated) migration to control MySQL-specific DDL:
BINARY(16) UUID keys, BIGINT UNSIGNED money, generated STORED column,
CHECK constraints and the extraction/index catalogue from schema.md.
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision = "0001_initial_schema"
down_revision = None
branch_labels = None
depends_on = None

TS = sa.text("CURRENT_TIMESTAMP(6)")
TS_ONUPDATE = sa.text("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)")


def _guid():
    return sa.BINARY(16)


def upgrade() -> None:
    # 1. customers
    op.create_table(
        "customers",
        sa.Column("customer_id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column("public_id", _guid(), nullable=False),
        sa.Column("display_name", sa.String(120), nullable=False),
        sa.Column("status", sa.String(16), nullable=False, server_default=sa.text("'active'")),
        sa.Column("data_origin", sa.String(16), nullable=False, server_default=sa.text("'manual'")),
        sa.Column("generation_run_id", sa.String(64), nullable=True),
        sa.Column("anonymized_at", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False, server_default=TS),
        sa.Column("updated_at", mysql.DATETIME(fsp=6), nullable=False, server_default=TS_ONUPDATE),
        sa.PrimaryKeyConstraint("customer_id"),
        sa.CheckConstraint("status in ('active','inactive')", name="ck_customers_status"),
        sa.CheckConstraint("data_origin in ('manual','synthetic')", name="ck_customers_data_origin"),
        mysql_engine="InnoDB",
    )
    op.create_index("uq_customers_public_id", "customers", ["public_id"], unique=True)
    op.create_index("ix_customers_updated_at_customer_id", "customers", ["updated_at", "customer_id"])

    # 2. customer_credentials
    op.create_table(
        "customer_credentials",
        sa.Column("customer_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("email_normalized", sa.String(320), nullable=False),
        sa.Column("password_hash", sa.String(255), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False, server_default=sa.text("1")),
        sa.Column("password_changed_at", mysql.DATETIME(fsp=6), nullable=False, server_default=TS),
        sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False, server_default=TS),
        sa.Column("updated_at", mysql.DATETIME(fsp=6), nullable=False, server_default=TS_ONUPDATE),
        sa.PrimaryKeyConstraint("customer_id"),
        sa.ForeignKeyConstraint(
            ["customer_id"], ["customers.customer_id"],
            name="fk_customer_credentials_customer_id", ondelete="RESTRICT",
        ),
        mysql_engine="InnoDB",
    )
    op.create_index(
        "uq_customer_credentials_email_normalized",
        "customer_credentials", ["email_normalized"], unique=True,
    )

    # 3. categories
    op.create_table(
        "categories",
        sa.Column("category_id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column("public_id", _guid(), nullable=False),
        sa.Column("parent_category_id", mysql.BIGINT(unsigned=True), nullable=True),
        sa.Column("code", sa.String(64), nullable=False),
        sa.Column("name", sa.String(160), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("1")),
        sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False, server_default=TS),
        sa.Column("updated_at", mysql.DATETIME(fsp=6), nullable=False, server_default=TS_ONUPDATE),
        sa.PrimaryKeyConstraint("category_id"),
        sa.ForeignKeyConstraint(
            ["parent_category_id"], ["categories.category_id"],
            name="fk_categories_parent_category_id", ondelete="RESTRICT",
        ),
        mysql_engine="InnoDB",
    )
    op.create_index("uq_categories_code", "categories", ["code"], unique=True)
    op.create_index("uq_categories_public_id", "categories", ["public_id"], unique=True)
    op.create_index(
        "ix_categories_parent_is_active_id",
        "categories", ["parent_category_id", "is_active", "category_id"],
    )
    op.create_index("ix_categories_updated_at_category_id", "categories", ["updated_at", "category_id"])

    # 4. products
    op.create_table(
        "products",
        sa.Column("product_id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column("public_id", _guid(), nullable=False),
        sa.Column("category_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("slug", sa.String(180), nullable=False),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("image_url", sa.String(1024), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("1")),
        sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False, server_default=TS),
        sa.Column("updated_at", mysql.DATETIME(fsp=6), nullable=False, server_default=TS_ONUPDATE),
        sa.PrimaryKeyConstraint("product_id"),
        sa.ForeignKeyConstraint(
            ["category_id"], ["categories.category_id"],
            name="fk_products_category_id", ondelete="RESTRICT",
        ),
        mysql_engine="InnoDB",
    )
    op.create_index("uq_products_slug", "products", ["slug"], unique=True)
    op.create_index("uq_products_public_id", "products", ["public_id"], unique=True)
    op.create_index(
        "ix_products_category_id_is_active_product_id",
        "products", ["category_id", "is_active", "product_id"],
    )
    op.create_index("ix_products_is_active_product_id", "products", ["is_active", "product_id"])
    op.create_index("ix_products_updated_at_product_id", "products", ["updated_at", "product_id"])

    # 5. product_variants
    op.create_table(
        "product_variants",
        sa.Column("variant_id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column("public_id", _guid(), nullable=False),
        sa.Column("product_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("sku", sa.String(64), nullable=False),
        sa.Column("size_code", sa.String(32), nullable=False),
        sa.Column("color_code", sa.String(64), nullable=False),
        sa.Column("price_vnd", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("1")),
        sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False, server_default=TS),
        sa.Column("updated_at", mysql.DATETIME(fsp=6), nullable=False, server_default=TS_ONUPDATE),
        sa.PrimaryKeyConstraint("variant_id"),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.product_id"],
            name="fk_product_variants_product_id", ondelete="RESTRICT",
        ),
        sa.CheckConstraint("price_vnd >= 0", name="ck_product_variants_price_non_negative"),
        mysql_engine="InnoDB",
    )
    op.create_index("uq_product_variants_sku", "product_variants", ["sku"], unique=True)
    op.create_index("uq_product_variants_public_id", "product_variants", ["public_id"], unique=True)
    op.create_index(
        "uq_product_variants_product_size_color",
        "product_variants", ["product_id", "size_code", "color_code"], unique=True,
    )
    op.create_index(
        "ix_product_variants_product_id_is_active_variant_id",
        "product_variants", ["product_id", "is_active", "variant_id"],
    )
    op.create_index(
        "ix_product_variants_updated_at_variant_id",
        "product_variants", ["updated_at", "variant_id"],
    )

    # 6. carts
    op.create_table(
        "carts",
        sa.Column("cart_id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column("public_id", _guid(), nullable=False),
        sa.Column("customer_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("status", sa.String(16), nullable=False, server_default=sa.text("'active'")),
        sa.Column(
            "active_customer_guard",
            mysql.BIGINT(unsigned=True),
            sa.Computed("(case when status = 'active' then customer_id else null end)", persisted=True),
            nullable=True,
        ),
        sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False, server_default=TS),
        sa.Column("updated_at", mysql.DATETIME(fsp=6), nullable=False, server_default=TS_ONUPDATE),
        sa.Column("checked_out_at", mysql.DATETIME(fsp=6), nullable=True),
        sa.PrimaryKeyConstraint("cart_id"),
        sa.ForeignKeyConstraint(
            ["customer_id"], ["customers.customer_id"],
            name="fk_carts_customer_id", ondelete="RESTRICT",
        ),
        sa.CheckConstraint("status in ('active','checked_out')", name="ck_carts_status"),
        mysql_engine="InnoDB",
    )
    op.create_index("uq_carts_public_id", "carts", ["public_id"], unique=True)
    op.create_index("uq_carts_active_customer_guard", "carts", ["active_customer_guard"], unique=True)
    op.create_index(
        "ix_carts_customer_id_created_at_cart_id",
        "carts", ["customer_id", "created_at", "cart_id"],
    )
    op.create_index("ix_carts_updated_at_cart_id", "carts", ["updated_at", "cart_id"])

    # 7. cart_items
    op.create_table(
        "cart_items",
        sa.Column("cart_item_id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column("cart_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("variant_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("quantity", mysql.INTEGER(unsigned=True), nullable=False),
        sa.Column("is_present", sa.Boolean(), nullable=False, server_default=sa.text("1")),
        sa.Column("first_added_at", mysql.DATETIME(fsp=6), nullable=False, server_default=TS),
        sa.Column("removed_at", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column("updated_at", mysql.DATETIME(fsp=6), nullable=False, server_default=TS_ONUPDATE),
        sa.PrimaryKeyConstraint("cart_item_id"),
        sa.ForeignKeyConstraint(
            ["cart_id"], ["carts.cart_id"],
            name="fk_cart_items_cart_id", ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"], ["product_variants.variant_id"],
            name="fk_cart_items_variant_id", ondelete="RESTRICT",
        ),
        sa.CheckConstraint("quantity > 0", name="ck_cart_items_quantity_positive"),
        sa.CheckConstraint(
            "(is_present = 1 and removed_at is null) or (is_present = 0 and removed_at is not null)",
            name="ck_cart_items_presence_removed_consistency",
        ),
        mysql_engine="InnoDB",
    )
    op.create_index(
        "uq_cart_items_cart_id_variant_id",
        "cart_items", ["cart_id", "variant_id"], unique=True,
    )
    op.create_index("ix_cart_items_variant_id_cart_item_id", "cart_items", ["variant_id", "cart_item_id"])
    op.create_index("ix_cart_items_updated_at_cart_item_id", "cart_items", ["updated_at", "cart_item_id"])

    # 8. orders
    op.create_table(
        "orders",
        sa.Column("order_id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column("order_number", sa.String(32), nullable=False),
        sa.Column("cart_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("customer_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("checkout_idempotency_key", sa.String(64), nullable=False),
        sa.Column("status", sa.String(24), nullable=False),
        sa.Column("currency_code", sa.CHAR(3), nullable=False, server_default=sa.text("'VND'")),
        sa.Column("subtotal_vnd", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("shipping_fee_vnd", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("total_vnd", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("receiver_name", sa.String(160), nullable=False),
        sa.Column("receiver_phone", sa.String(32), nullable=False),
        sa.Column("shipping_address_text", sa.String(1000), nullable=False),
        sa.Column("data_origin", sa.String(16), nullable=False, server_default=sa.text("'manual'")),
        sa.Column("generation_run_id", sa.String(64), nullable=True),
        sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False, server_default=TS),
        sa.Column("updated_at", mysql.DATETIME(fsp=6), nullable=False, server_default=TS_ONUPDATE),
        sa.Column("paid_at", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column("completed_at", mysql.DATETIME(fsp=6), nullable=True),
        sa.PrimaryKeyConstraint("order_id"),
        sa.ForeignKeyConstraint(
            ["cart_id"], ["carts.cart_id"], name="fk_orders_cart_id", ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"], ["customers.customer_id"], name="fk_orders_customer_id", ondelete="RESTRICT",
        ),
        sa.CheckConstraint("status in ('paid','payment_failed','completed')", name="ck_orders_status"),
        sa.CheckConstraint("currency_code = 'VND'", name="ck_orders_currency_code"),
        sa.CheckConstraint("subtotal_vnd >= 0", name="ck_orders_subtotal_non_negative"),
        sa.CheckConstraint("shipping_fee_vnd >= 0", name="ck_orders_shipping_fee_non_negative"),
        sa.CheckConstraint("total_vnd = subtotal_vnd + shipping_fee_vnd", name="ck_orders_total_arithmetic"),
        sa.CheckConstraint("data_origin in ('manual','synthetic')", name="ck_orders_data_origin"),
        mysql_engine="InnoDB",
    )
    op.create_index("uq_orders_order_number", "orders", ["order_number"], unique=True)
    op.create_index("uq_orders_cart_id", "orders", ["cart_id"], unique=True)
    op.create_index(
        "uq_orders_checkout_idempotency_key", "orders", ["checkout_idempotency_key"], unique=True,
    )
    op.create_index(
        "ix_orders_customer_id_created_at_order_id",
        "orders", ["customer_id", "created_at", "order_id"],
    )
    op.create_index("ix_orders_status_created_at_order_id", "orders", ["status", "created_at", "order_id"])
    op.create_index("ix_orders_updated_at_order_id", "orders", ["updated_at", "order_id"])

    # 9. order_items
    op.create_table(
        "order_items",
        sa.Column("order_item_id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column("order_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("variant_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("product_public_id_snapshot", _guid(), nullable=False),
        sa.Column("category_code_snapshot", sa.String(64), nullable=False),
        sa.Column("category_name_snapshot", sa.String(160), nullable=False),
        sa.Column("product_name_snapshot", sa.String(200), nullable=False),
        sa.Column("sku_snapshot", sa.String(64), nullable=False),
        sa.Column("size_code_snapshot", sa.String(32), nullable=False),
        sa.Column("color_code_snapshot", sa.String(64), nullable=False),
        sa.Column("unit_price_vnd", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("quantity", mysql.INTEGER(unsigned=True), nullable=False),
        sa.Column("line_total_vnd", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False, server_default=TS),
        sa.PrimaryKeyConstraint("order_item_id"),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.order_id"], name="fk_order_items_order_id", ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"], ["product_variants.variant_id"],
            name="fk_order_items_variant_id", ondelete="RESTRICT",
        ),
        sa.CheckConstraint("unit_price_vnd >= 0", name="ck_order_items_unit_price_non_negative"),
        sa.CheckConstraint("quantity > 0", name="ck_order_items_quantity_positive"),
        sa.CheckConstraint(
            "line_total_vnd = unit_price_vnd * quantity", name="ck_order_items_line_total_arithmetic",
        ),
        mysql_engine="InnoDB",
    )
    op.create_index(
        "uq_order_items_order_id_variant_id", "order_items", ["order_id", "variant_id"], unique=True,
    )
    op.create_index("ix_order_items_variant_id_order_item_id", "order_items", ["variant_id", "order_item_id"])
    op.create_index("ix_order_items_created_at_order_item_id", "order_items", ["created_at", "order_item_id"])

    # 10. payments
    op.create_table(
        "payments",
        sa.Column("payment_id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column("payment_reference", sa.String(64), nullable=False),
        sa.Column("order_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("payment_idempotency_key", sa.String(64), nullable=False),
        sa.Column("status", sa.String(16), nullable=False),
        sa.Column("currency_code", sa.CHAR(3), nullable=False, server_default=sa.text("'VND'")),
        sa.Column("amount_vnd", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("simulator_scenario", sa.String(32), nullable=False),
        sa.Column("failure_code", sa.String(64), nullable=True),
        sa.Column("attempted_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False, server_default=TS),
        sa.PrimaryKeyConstraint("payment_id"),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.order_id"], name="fk_payments_order_id", ondelete="RESTRICT",
        ),
        sa.CheckConstraint("status in ('succeeded','failed')", name="ck_payments_status"),
        sa.CheckConstraint("currency_code = 'VND'", name="ck_payments_currency_code"),
        sa.CheckConstraint("amount_vnd >= 0", name="ck_payments_amount_non_negative"),
        sa.CheckConstraint(
            "(status = 'succeeded' and failure_code is null) "
            "or (status = 'failed' and failure_code is not null)",
            name="ck_payments_failure_code_consistency",
        ),
        mysql_engine="InnoDB",
    )
    op.create_index("uq_payments_payment_reference", "payments", ["payment_reference"], unique=True)
    op.create_index("uq_payments_order_id", "payments", ["order_id"], unique=True)
    op.create_index(
        "uq_payments_payment_idempotency_key", "payments", ["payment_idempotency_key"], unique=True,
    )
    op.create_index("ix_payments_created_at_payment_id", "payments", ["created_at", "payment_id"])

    # 11. order_status_history
    op.create_table(
        "order_status_history",
        sa.Column(
            "order_status_history_id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False,
        ),
        sa.Column("order_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("from_status", sa.String(24), nullable=True),
        sa.Column("to_status", sa.String(24), nullable=False),
        sa.Column("transition_source", sa.String(32), nullable=False),
        sa.Column("reason", sa.String(500), nullable=True),
        sa.Column("transition_idempotency_key", sa.String(64), nullable=False),
        sa.Column("transitioned_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False, server_default=TS),
        sa.PrimaryKeyConstraint("order_status_history_id"),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.order_id"],
            name="fk_order_status_history_order_id", ondelete="RESTRICT",
        ),
        sa.CheckConstraint(
            "(from_status is null and to_status in ('paid','payment_failed')) "
            "or (from_status = 'paid' and to_status = 'completed')",
            name="ck_order_status_history_valid_transition",
        ),
        sa.CheckConstraint(
            "transition_source in ('checkout','internal_endpoint','generator','system')",
            name="ck_order_status_history_transition_source",
        ),
        mysql_engine="InnoDB",
    )
    op.create_index(
        "uq_order_status_history_transition_idempotency_key",
        "order_status_history", ["transition_idempotency_key"], unique=True,
    )
    op.create_index(
        "uq_order_status_history_order_id_to_status",
        "order_status_history", ["order_id", "to_status"], unique=True,
    )
    op.create_index(
        "ix_order_status_history_order_id_transitioned_at_id",
        "order_status_history", ["order_id", "transitioned_at", "order_status_history_id"],
    )
    op.create_index(
        "ix_order_status_history_created_at_id",
        "order_status_history", ["created_at", "order_status_history_id"],
    )

    # 12. inventory
    op.create_table(
        "inventory",
        sa.Column("variant_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("opening_on_hand", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("on_hand", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("version", mysql.BIGINT(unsigned=True), nullable=False, server_default=sa.text("0")),
        sa.Column("updated_at", mysql.DATETIME(fsp=6), nullable=False, server_default=TS_ONUPDATE),
        sa.PrimaryKeyConstraint("variant_id"),
        sa.ForeignKeyConstraint(
            ["variant_id"], ["product_variants.variant_id"],
            name="fk_inventory_variant_id", ondelete="RESTRICT",
        ),
        sa.CheckConstraint("opening_on_hand >= 0", name="ck_inventory_opening_on_hand_non_negative"),
        sa.CheckConstraint("on_hand >= 0", name="ck_inventory_on_hand_non_negative"),
        sa.CheckConstraint("on_hand <= opening_on_hand", name="ck_inventory_on_hand_within_opening"),
        mysql_engine="InnoDB",
    )
    op.create_index("ix_inventory_updated_at_variant_id", "inventory", ["updated_at", "variant_id"])


def downgrade() -> None:
    op.drop_table("inventory")
    op.drop_table("order_status_history")
    op.drop_table("payments")
    op.drop_table("order_items")
    op.drop_table("orders")
    op.drop_table("cart_items")
    op.drop_table("carts")
    op.drop_table("product_variants")
    op.drop_table("products")
    op.drop_table("categories")
    op.drop_table("customer_credentials")
    op.drop_table("customers")
