#!/bin/bash
set -e

mysql --protocol=socket -uroot -p"${MYSQL_ROOT_PASSWORD}" <<SQL
CREATE USER IF NOT EXISTS '${MYSQL_ANALYTICS_READER_USER}'@'%' IDENTIFIED BY '${MYSQL_ANALYTICS_READER_PASSWORD}';
GRANT SELECT ON \`${MYSQL_DATABASE}\`.* TO '${MYSQL_ANALYTICS_READER_USER}'@'%';
FLUSH PRIVILEGES;
SQL
